// Code generated by entc, DO NOT EDIT.

package pet

import (
	"time"
)

const (
	// Label holds the string label denoting the pet type in the database.
	Label = "pet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"

	// EdgeTtID holds the string denoting the tt_id edge name in mutations.
	EdgeTtID = "tt_id"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the pet in the database.
	Table = "pets"
	// TtIDTable is the table the holds the tt_id relation/edge.
	TtIDTable = "pets"
	// TtIDInverseTable is the table name for the Tt entity.
	// It exists in this package in order to avoid circular dependency with the "tt" package.
	TtIDInverseTable = "tts"
	// TtIDColumn is the table column denoting the tt_id relation/edge.
	TtIDColumn = "id_tt"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "pets"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_id"
)

// Columns holds all SQL columns for pet fields.
var Columns = []string{
	FieldID,
	FieldCreateAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Pet type.
var ForeignKeys = []string{
	"id_tt",
	"user_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() time.Time
)
