// Code generated by entc, DO NOT EDIT.

package tt

const (
	// Label holds the string label denoting the tt type in the database.
	Label = "tt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// EdgeIDTt holds the string denoting the id_tt edge name in mutations.
	EdgeIDTt = "id_tt"

	// Table holds the table name of the tt in the database.
	Table = "tts"
	// IDTtTable is the table the holds the id_tt relation/edge.
	IDTtTable = "pets"
	// IDTtInverseTable is the table name for the Pet entity.
	// It exists in this package in order to avoid circular dependency with the "pet" package.
	IDTtInverseTable = "pets"
	// IDTtColumn is the table column denoting the id_tt relation/edge.
	IDTtColumn = "id_tt"
)

// Columns holds all SQL columns for tt fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
