// Code generated by entc, DO NOT EDIT.

package ent

import (
	"test-go/ent/pet"
	"test-go/ent/schema"
	"test-go/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescCreateAt is the schema descriptor for create_at field.
	petDescCreateAt := petFields[0].Descriptor()
	// pet.DefaultCreateAt holds the default value on creation for the create_at field.
	pet.DefaultCreateAt = petDescCreateAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateAt is the schema descriptor for create_at field.
	userDescCreateAt := userFields[0].Descriptor()
	// user.DefaultCreateAt holds the default value on creation for the create_at field.
	user.DefaultCreateAt = userDescCreateAt.Default.(func() time.Time)
}
