// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"test-go/ent/pet"
	"test-go/ent/tt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// TtCreate is the builder for creating a Tt entity.
type TtCreate struct {
	config
	mutation *TtMutation
	hooks    []Hook
}

// AddIDTtIDs adds the "id_tt" edge to the Pet entity by IDs.
func (tc *TtCreate) AddIDTtIDs(ids ...int) *TtCreate {
	tc.mutation.AddIDTtIDs(ids...)
	return tc
}

// AddIDTt adds the "id_tt" edges to the Pet entity.
func (tc *TtCreate) AddIDTt(p ...*Pet) *TtCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tc.AddIDTtIDs(ids...)
}

// Mutation returns the TtMutation object of the builder.
func (tc *TtCreate) Mutation() *TtMutation {
	return tc.mutation
}

// Save creates the Tt in the database.
func (tc *TtCreate) Save(ctx context.Context) (*Tt, error) {
	var (
		err  error
		node *Tt
	)
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TtMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TtCreate) SaveX(ctx context.Context) *Tt {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (tc *TtCreate) check() error {
	return nil
}

func (tc *TtCreate) sqlSave(ctx context.Context) (*Tt, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TtCreate) createSpec() (*Tt, *sqlgraph.CreateSpec) {
	var (
		_node = &Tt{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tt.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tt.FieldID,
			},
		}
	)
	if nodes := tc.mutation.IDTtIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tt.IDTtTable,
			Columns: []string{tt.IDTtColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TtCreateBulk is the builder for creating many Tt entities in bulk.
type TtCreateBulk struct {
	config
	builders []*TtCreate
}

// Save creates the Tt entities in the database.
func (tcb *TtCreateBulk) Save(ctx context.Context) ([]*Tt, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tt, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TtMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TtCreateBulk) SaveX(ctx context.Context) []*Tt {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
