// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Pet is the predicate function for pet builders.
type Pet func(*sql.Selector)

// Tt is the predicate function for tt builders.
type Tt func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
